### PR TITLE
Ej context fix

### LINKED ISSUE #8: Ara Context should cache the `Web3` object
## Expected Behavior
- Ara Context should cache existing providers so that new `Web3` instances are not created when `ara-context` is `required`.

## Actual Behavior
- Each time `ara-context` is `required`, a new `Web3` object and provider are instantiated.

## Steps to Reproduce the Problem

  1. Add `ara-context` as a dependency to a project
  2. `require('ara-context')()`

### PR DESCRIPTION
**Pull request by mahjiang**
Changes to allow users of `ara-context` to manage the connection. Fixes #8

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -19,9 +21,33 @@ function context(opts) {
...
     web3: web3.load(opts.web3)
   }
 
+  ctx.close = () => {
+    if (ctx.web3 && ctx.web3.currentProvider && ctx.web3.currentProvider.connection) {
+      ctx.web3.currentProvider.connection.close()
+    }
+  }
+
+  ctx.ready = pify(thunky(async (done) => {
```
Comment (jwerle) [inline index.js]: No need for the `async` keyword here

File: web3.js [hunk 2]
```diff
@@ -22,6 +22,9 @@ function load(opts) {
     opts = {}
   }
   if (!opts.provider) {
+    if (false === opts.provider) {
```
Comment (jwerle) [inline web3.js]: :raised_hands:

Comment (cckelly) [reply web3.js]: 👎
